import { Command } from "commander";
import { gplCommand } from "./gpl.command";
import { gphCommand } from "./gph.command";
import { gaCommand } from "./ga.command";
import { gcmCommand } from "./gcm.command";
import { gsCommand } from "./gs.command";
import { gcoCommand } from "./gco.command";
import { gcobCommand } from "./gcob.command";
import { bgCommand } from "./bg.command";
import { grCommand } from "./gr.command";
import { gpuCommand } from "./gpu.command";
import { gphoCommand } from "./gpho.command";
import { gploCommand } from "./gplo.command";
import { initCommand } from "./init.command";
import { fetchCommand } from "./fetch.command";
import { mergeCommand } from "./merge.command";
import { syncCommand } from "./sync.command";
import { cleanupCommand } from "./cleanup.command";
import { graphCommand } from "./graph.command";
import { undoCommand } from "./undo.command";
import { cpCommand } from "./cp.command";
import { delCommand } from "./del.command";
import { finalCommand } from "./final.command";
import { untrackCommand } from "./untrack.command";

export function registerGitCommands(program: Command) {
  const git = program.command("git").description("Git utilities");
  gplCommand(git);
  gphCommand(git);
  gaCommand(git);
  gcmCommand(git);
  gsCommand(git);
  gcoCommand(git);
  gcobCommand(git);
  bgCommand(git);
  grCommand(git);
  gpuCommand(git);
  gphoCommand(git);
  gploCommand(git);
  initCommand(git);
  fetchCommand(git);
  mergeCommand(git);
  syncCommand(git);
  cleanupCommand(git);
  graphCommand(git);
  undoCommand(git);
  cpCommand(git);
  delCommand(git);
  finalCommand(git);
  untrackCommand(git);
}
